# -------- Build stage --------
FROM node:20-alpine AS builder
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy code + env
COPY . .
# ... (after npm install)

ARG MONGODB_URI
ARG JWT_SECRET
ARG GMAIL_USER
ARG GMAIL_APP_PASSWORD
ARG NEXT_PUBLIC_BASE_URL
ARG NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
ARG STRIPE_SECRET_KEY
ARG STRIPE_WEBHOOK_SECRET
ARG EMAIL_USER
ARG EMAIL_PASS
ARG EMAIL_HOST
ARG EMAIL_PORT

ENV MONGODB_URI=$MONGODB_URI \
    JWT_SECRET=$JWT_SECRET \
    GMAIL_USER=$GMAIL_USER \
    GMAIL_APP_PASSWORD=$GMAIL_APP_PASSWORD \
    NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL \
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY \
    STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY \
    STRIPE_WEBHOOK_SECRET=$STRIPE_WEBHOOK_SECRET \
    EMAIL_USER=$EMAIL_USER \
    EMAIL_PASS=$EMAIL_PASS \
    EMAIL_HOST=$EMAIL_HOST \
    EMAIL_PORT=$EMAIL_PORT

RUN npm run build
# ...

# Build Next.js
RUN npm run build

# -------- Serve stage --------
FROM node:20-alpine
WORKDIR /app

COPY --from=builder /app .

EXPOSE 3000
CMD ["npm", "start"]
